# Generated by Django 4.1.6 on 2023-02-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('middle', 'Middle'), ('low', 'Low')], default='high', max_length=15),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('process', 'Process'), ('finished', 'Finished')], default='pending', max_length=30),
        ),
    ]
